WebApp/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Data;

namespace WebApp
{
    public class CandidatesController : Controller
    {
        private WebDbContext db = new WebDbContext();

        // GET: Candidates
        public ActionResult Index()
        {
            return View(db.Candidates.ToList());
        }

        // GET: Candidates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Using low tier tricks to break my code such as using 'null' values.";
                return RedirectToAction("Index");
            }
            Candidate candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Dr. Pasparakis do not underestimate my low tier Brain.";
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // GET: Candidates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Candidates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CandidateNumber,FirstName,MiddleName,LastName,Gender,NativeLanguage,CountryOfResidence,Birthdate,Email,LandLineNumber,MobileNumber,Address1,Address2,PostalCode,Town,Province,PhotoIdType,PhotoIdNumber,PhotoIdDate")] Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                db.Candidates.Add(candidate);
                db.SaveChanges();
                TempData["messageSuccess"] = $"Candidate with ID {candidate.CandidateNumber} was Summoned successfuly";
                return RedirectToAction("Index");
            }

            return View(candidate);
        }

        // GET: Candidates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Using low tier tricks to break my code such as using 'null' values.";
                return RedirectToAction("Index");
            }
            var candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Dr. Pasparakis do not underestimate my low tier Brain.";
                return RedirectToAction("Index");
            }
            var viewModel = new Candidate();
            viewModel.PhotoIdDate = candidate.PhotoIdDate;
            viewModel.Birthdate = candidate.Birthdate;

            return View(candidate);
        }

        // POST: Candidates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CandidateNumber,FirstName,MiddleName,LastName,Gender,NativeLanguage,CountryOfResidence,Birthdate,Email,LandLineNumber,MobileNumber,Address1,Address2,PostalCode,Town,Province,PhotoIdType,PhotoIdNumber,PhotoIdDate")] Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidate).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["messageSuccess"] = $"Candidate with ID {candidate.CandidateNumber} was Updated successfuly";
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // GET: Candidates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Using low tier tricks to break my code such as using 'null' values.";
                return RedirectToAction("Index");
            }
            Candidate candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Dr. Pasparakis do not underestimate my low tier Brain.";
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            
            Candidate candidate = db.Candidates.Find(id);
            db.Candidates.Remove(candidate);
            db.SaveChanges();
            TempData["messageError"] = $"Candidate with id {id} was succesfully Assassinated";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Averkios Karalis is da best YAY</title>
    <link rel="icon" type="image/svg" href="~/Photos/favicon-16x16.png" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    @Scripts.Render("~/bundles/bootstrap.min.js")
    @Scripts.Render("~/bundles/bootstrap.bundle.min.js")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container mt-3">
            <div class="container-fluid">

                @Html.ActionLink("Averkios Karalis Assignment 3B", "Rick", "Home",new { area = "" }, new { @class = "navbar-brand" })
                <ul class="nav nav-pills">
                    <li class="nav nav-item">
                        <span class="nav-link active" href="#">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { id = "ot" })</span>
                    </li>
                    <li class="nav nav-item">
                        <span class="nav-link active" href="#">@Html.ActionLink("About", "About", "Home", new { area = "" }, new { id = "ot" })</span>
                    </li>
                    <li class="nav nav-item">
                        <span class="nav-link active" href="#">@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { id = "ot" })</span>
                    </li>
                    <li class="nav nav-item">
                        <span class="nav-link active" href="#">@Html.ActionLink("Candidate List", "Index", "Candidates", new { area = "" }, new { id = "ot" })</span>
                    </li>
                </ul>

            </div>
        </div>
    </div>


    <main class="container mt-4" >
        @RenderBody()
    </main>
        <footer class="container py-3 mt-4 align-bottom">


            <hr class="changetoorange" />
            <span style="font-weight:bold">this is a footer</span>
            <p>You can click <i>"Averkios Karalis Assignment 3B"</i> to return here</p>
            <div>
                <p>&copy; @DateTime.Now - The most amazingest web application in the whole world wide web</p>
                <p class="text-muted">
                    Do not question my aesthetic choices. I want to make this kitsch.
                    I also have mercy on your eyes, by using Dark theme.
                    Yes the Copyright is being updated every second.
                </p>
            </div>
        </footer>
   

    @Scripts.Render("~/bundles/jquery")

    @RenderSection("scripts", required: false)
</body>
</html>