WebApp/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Data;

namespace WebApp
{
    public class CandidatesController : Controller
    {
        private WebDbContext db = new WebDbContext();

        // GET: Candidates
        public ActionResult Index()
        {
            return View(db.Candidates.ToList());
        }

        // GET: Candidates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Using low tier tricks to break my code such as using 'null' values.";
                return RedirectToAction("Index");
            }
            Candidate candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Dr. Pasparakis do not underestimate my low tier Brain.";
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // GET: Candidates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Candidates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CandidateNumber,FirstName,MiddleName,LastName,Gender,NativeLanguage,CountryOfResidence,Birthdate,Email,LandLineNumber,MobileNumber,Address1,Address2,PostalCode,Town,Province,PhotoIdType,PhotoIdNumber,PhotoIdDate")] Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                db.Candidates.Add(candidate);
                db.SaveChanges();
                TempData["messageSuccess"] = $"Candidate with ID {candidate.CandidateNumber} was Summoned successfuly";
                return RedirectToAction("Index");
            }

            return View(candidate);
        }

        // GET: Candidates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Using low tier tricks to break my code such as using 'null' values.";
                return RedirectToAction("Index");
            }
            var candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Dr. Pasparakis do not underestimate my low tier Brain.";
                return RedirectToAction("Index");
            }
            var viewModel = new Candidate();
            viewModel.PhotoIdDate = candidate.PhotoIdDate;
            viewModel.Birthdate = candidate.Birthdate;

            return View(candidate);
        }

        // POST: Candidates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CandidateNumber,FirstName,MiddleName,LastName,Gender,NativeLanguage,CountryOfResidence,Birthdate,Email,LandLineNumber,MobileNumber,Address1,Address2,PostalCode,Town,Province,PhotoIdType,PhotoIdNumber,PhotoIdDate")] Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidate).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["messageSuccess"] = $"Candidate with ID {candidate.CandidateNumber} was Updated successfuly";
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // GET: Candidates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Using low tier tricks to break my code such as using 'null' values.";
                return RedirectToAction("Index");
            }
            Candidate candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Dr. Pasparakis do not underestimate my low tier Brain.";
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            
            Candidate candidate = db.Candidates.Find(id);
            db.Candidates.Remove(candidate);
            db.SaveChanges();
            TempData["messageError"] = $"Candidate with id {id} was succesfully Assassinated";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApp/Controllers/CertificatesController.cs
using Microsoft.AspNetCore.Mvc.Infrastructure;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Data;

namespace WebApp
{
    public class CertificatesController : Controller
    {
        private WebDbContext db = new WebDbContext();

        // GET: Certificates
    

        // GET: Certificates/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found. Using low tier tricks to break my code such as using 'null' values.";
                return RedirectToAction("Index", "Home");
            }
            Certificate certificate = db.Certificates.Find(id);
            if (certificate == null)
            {
                TempData["messageError"] = $"Error: Candidate with id {id} was not found.";
                return RedirectToAction("Index", "Home");
            }
            return View(certificate);
        }

        // GET: Certificates/Create
        public ActionResult Create()
        {
            ViewBag.CandidateNumber = new SelectList(db.Candidates, "CandidateNumber", "FirstName");
            ViewBag.Title = new SelectList(db.CertificateTitles, "Title", "Title");
            return View();
        }

        // POST: Certificates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CertificateId,Title,CandidateNumber,AssessmentTestCode,ExaminationDate,ScoreReportDate,CandidateScore,MaximumScore,AssessmentResultLabel,PercentageScore")] Certificate certificate)
        {
            if (ModelState.IsValid)
            {
                db.Certificates.Add(certificate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CandidateNumber = new SelectList(db.Candidates, "CandidateNumber", "FirstName", certificate.CandidateNumber);
            ViewBag.Title = new SelectList(db.CertificateTitles, "Title", "Title", certificate.Title);
            return View(certificate);
        }

        // GET: Certificates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Certificate certificate = db.Certificates.Find(id);
            if (certificate == null)
            {
                return HttpNotFound();
            }
            ViewBag.CandidateNumber = new SelectList(db.Candidates, "CandidateNumber", "FirstName", certificate.CandidateNumber);
            ViewBag.Title = new SelectList(db.CertificateTitles, "Title", "Title", certificate.Title);
            return View(certificate);
        }

        // POST: Certificates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CertificateId,Title,CandidateNumber,AssessmentTestCode,ExaminationDate,ScoreReportDate,CandidateScore,MaximumScore,AssessmentResultLabel,PercentageScore")] Certificate certificate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(certificate).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CandidateNumber = new SelectList(db.Candidates, "CandidateNumber", "FirstName", certificate.CandidateNumber);
            ViewBag.Title = new SelectList(db.CertificateTitles, "Title", "Title", certificate.Title);
            return View(certificate);
        }

        // GET: Certificates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Certificate certificate = db.Certificates.Find(id);
            if (certificate == null)
            {
                return HttpNotFound();
            }
            return View(certificate);
        }

        // POST: Certificates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Certificate certificate = db.Certificates.Find(id);
            db.Certificates.Remove(certificate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApp/Views/Candidates/Create.cshtml
@model WebApp.Data.Candidate

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Create Candidate";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-horizontal dark">
            <h4>Candidate</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter First Name" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Middle Name" } })

                    @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Last Name" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Gender, new SelectList(new List<SelectListItem>{

                        new SelectListItem { Value = "", Text = "--Select Gender--" },
                        new SelectListItem { Value = "Male", Text = "Male" },
                        new SelectListItem { Value = "Female", Text = "Female" },
                        new SelectListItem { Value = "O", Text = "Other" }
                    }, "value", "text"), new { @class = "form-control  bg-dark text-secondary" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NativeLanguage, htmlAttributes: new { @class = "control-label col-md-2 " })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NativeLanguage, new { htmlAttributes = new { @class = " form-control whttxt bg-dark ", placeholder = "Enter Native Language" } })
                    @Html.ValidationMessageFor(model => model.NativeLanguage, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CountryOfResidence, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CountryOfResidence, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Country of Residence" } })
                    @Html.ValidationMessageFor(model => model.CountryOfResidence, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Birthdate, new { @class = "form-control bg-dark whttxt", type = "date" })
                    @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "mail@adress.com" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LandLineNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LandLineNumber, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Landline Phone Number" } })
                    @Html.ValidationMessageFor(model => model.LandLineNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Mobile number" } })
                    @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Street Name" } })
                    @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Street Number" } })
                    @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Postal Code" } })
                    @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Town, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Town, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Town Name" } })
                    @Html.ValidationMessageFor(model => model.Town, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control whttxt bg-dark", placeholder = "Enter Province Name" } })
                    @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhotoIdType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.PhotoIdType, new SelectList(new List<SelectListItem>{

                       new SelectListItem { Value = "", Text = "--Select ID Type--" },
                       new SelectListItem { Value = "NationalIDCard", Text = "National ID Card" },
                       new SelectListItem { Value = "Passport", Text = "Passport" }
                   }, "value", "text"), new { @class = "form-control  bg-dark text-secondary" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
                @Html.ValidationMessageFor(model => model.PhotoIdType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoIdNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.EditorFor(model => model.PhotoIdNumber, new { htmlAttributes = new { @class = "form-control  whttxt bg-dark", placeholder = "Enter ID Number" } })
                @Html.ValidationMessageFor(model => model.PhotoIdNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoIdDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(model => model.PhotoIdDate, new { @class = "form-control bg-dark whttxt", type = "date" })
                @Html.ValidationMessageFor(model => model.PhotoIdDate, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group mt-2">

            <button type="submit" class="btn btn-outline-success">Create Candidate</button> |
            

            <button type="submit" class="btn btn-info">@Html.ActionLink("Back to List", "Index")</button>

        </div>

    }


</body>
</html>

WebApp/Views/Candidates/Details.cshtml
@model WebApp.Data.Candidate

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Details of a Candidate";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <h3 style="text-align:center;">Candidate Details</h3>
    <hr />
    <h4 style="text-align:center;">You can't edit here</h4>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <table id="myTable" class="table table-bordered changecolortored">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.FirstName)</th>
                            <th>@Html.DisplayNameFor(model => model.MiddleName)</th>
                            <th>@Html.DisplayNameFor(model => model.LastName)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.FirstName)</td>
                            <td>@Html.DisplayFor(model => model.MiddleName)</td>
                            <td>@Html.DisplayFor(model => model.LastName)</td>
                        </tr>
                    </tbody>

                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Gender)</th>
                            <th>@Html.DisplayNameFor(model => model.NativeLanguage)</th>
                            <th>@Html.DisplayNameFor(model => model.CountryOfResidence)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.Gender)</td>
                            <td>@Html.DisplayFor(model => model.NativeLanguage)</td>
                            <td>@Html.DisplayFor(model => model.CountryOfResidence)</td>
                        </tr>
                    </tbody>

                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Birthdate)</th>
                            <th>@Html.DisplayNameFor(model => model.Email)</th>
                            <th>@Html.DisplayNameFor(model => model.LandLineNumber)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.Birthdate)</td>
                            <td>@Html.DisplayFor(model => model.Email)</td>
                            <td>@Html.DisplayFor(model => model.LandLineNumber)</td>
                        </tr>
                    </tbody>

                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.MobileNumber)</th>
                            <th>@Html.DisplayNameFor(model => model.Address1)</th>
                            <th>@Html.DisplayNameFor(model => model.Address2)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.MobileNumber)</td>
                            <td>@Html.DisplayFor(model => model.Address1)</td>
                            <td>@Html.DisplayFor(model => model.Address2)</td>
                        </tr>
                    </tbody>

                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.PostalCode)</th>
                            <th>@Html.DisplayNameFor(model => model.Town)</th>
                            <th>@Html.DisplayNameFor(model => model.Province)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.PostalCode)</td>
                            <td>@Html.DisplayFor(model => model.Town)</td>
                            <td>@Html.DisplayFor(model => model.Province)</td>
                        </tr>
                    </tbody>

                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.PhotoIdType)</th>
                            <th>@Html.DisplayNameFor(model => model.PhotoIdNumber)</th>
                            <th>@Html.DisplayNameFor(model => model.PhotoIdDate)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.PhotoIdType)</td>
                            <td>@Html.DisplayFor(model => model.PhotoIdNumber)</td>
                            <td>@Html.DisplayFor(model => model.PhotoIdDate)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <p>
        <button type="button" class="btn btn-primary">@Html.ActionLink("Edit", "Edit", new { id = Model.CandidateNumber })</button>
        |
        <button type="button" class="btn btn-outline-primary">@Html.ActionLink("Results", "Details", "Certificates", new { id = Model.CandidateNumber }, new { id = "" })</button>
      
        |
        <button type="button" class="btn btn-info">@Html.ActionLink("Back to List", "Index")</button>
    </p>
</body>
</html>